### ISSUE TITLE
关于OpenSSL这个库的设计问题

### ISSUE THREAD

**Issue by idada** [xindong/frontd#2]
看了一下`github.com/Luzifer/go-openssl`这个库的代码，发现里面的接口设计不太合理，接收的参数使用`string`类型内部再转成`[]byte`使用，而调用者手头有`[]byte`时还得转成`string`给它，这样来回转换徒增数据拷贝次数。

建议把这个库的代码copy到项目里改改或者fork一个来改，参数统一用`[]byte`，顺便也减少第三方库依赖。

**Comment by tomasen** [comment]
just migrated this package to local and made some changes [1d8df601ac00156e33996bb4804633707e5af22f]
