### ISSUE TITLE
关于pprof

### ISSUE THREAD

**Issue by idada** [xindong/frontd#3]
线上项目经常会需要用到pprof监控项目，建议添加pprof相关的命令接口或者用go自带的`net/http/pprof`。

自己提供命令接口的好处是可以减少配置量少占用一个端口，用自带的`net/http/pprof`的好处是工具配套全，不用自己再手工到服务器上下载pprof数据。

之前都是自己造轮子，但新项目上我倾向于用`net/http/pprof`。

端口配置问题可以用+1的方式来省掉手工，比如frontd端口在1234，frontd的pprof接口就是1235。

**Comment by tomasen** [comment]
通过配置环境变量启动： [4d1e37144f3075ea85bc9ce471664ef9d171d48c]

**Comment by idada** [comment]
环境变量没办法在线修改，比如线上遇到卡顿延迟，这时候要立即开启线上监控时候就不行了

**Comment by tomasen** [comment]
这个需求，如README中默认启动时就加入这个变量即可。

暂时还是想把这个控制权留在部署时
