### ISSUE TITLE
接受新连接失败，直接Fatal是不是不合适

### ISSUE THREAD

**Issue by daizong** [xindong/frontd#4]
<pre><code> 
for {
		conn, err := l.Accept()
		if err != nil {
			log.Fatal(err)
		}
		go handleConn(conn)
	}
<code><pre>
接受新连接失败，直接Fatal是不是不合适，已经建立传输的连接会断掉。

**Comment by idada** [comment]
我提交了个pr，从`net/http`包里学来的重试算法，这样就不会一次Accept失败直接让服务器挂了。

但是如果是Accept硬失败，直接让服务器挂比让它继续跑着要好，可以马上暴露出问题。
